Correction of BUG in subroutine parser and Support for multiple terminals
OlegKunitsyn/gnucobol-debug pull request #141
Opened 2023-11-29 18:05 UTC by marcsosduma

Support for multiple terminals – allows the Linux system to use not only XTerm but also gnome-terminal, konsole (KDE), and xfce4-terminal.

Bug in parser – in some cases, the snippet "// fix new codegen - new" was causing the parser to change the line number of the corresponding C code line after the "/* Program exit */" tag.

2023-11-29 18:35 UTC, GitMensch requested changes
Can we have an adjusted setting to let the user choose?

2023-11-29 18:35 UTC, GitMensch commented on src/mi2.ts
> +            }
thee should be configurable a gdbtty to enable choosing, otherwise LGTM

2023-12-01 02:04 UTC, marcsosduma commented on src/mi2.ts
> +            }
Hello Simon! Something like this? "gdbtty": "xfce4"

2023-12-01 14:10 UTC, GitMensch commented on src/mi2.ts
> +            }
exactly

2023-12-02 12:51 UTC, marcsosduma commented on src/mi2.ts
> +            }
Hello Simon! When you have a moment, take a look and see if it's okay.

2023-12-02 17:14 UTC, GitMensch approved these changes
Nice one! I personally would prefer two commits - one for the parser fix and one for the new feature, but that's not my repo...

I do think that the parser fix should include a change in the testsuite.

2023-12-02 17:14 UTC, GitMensch commented on src/parser.c.ts
> +    private isVersion2_2_or_3_1_1: boolean = false;
A trailing space slipped in here - otherwise it the changes LGTM.

2023-12-03 15:36 UTC, marcsosduma commented
Hello Simon! The tests pass, but I found the issue while debugging these files 'sample.cbl', 'subsample.cbl', and 'subsubsample.cbl'. When the system switches from one file to another, for example, from 'sample' to 'subsample', the debugger goes to the last line of code. With this correction, it seems that the problem is resolved.

2024-01-16 11:24 UTC, GitMensch commented
I hop that @OlegKunitsyn may merge this soon.

In any case and "mostly unrelated" (at least unrelated to this repo, other than your changes being likely similar): can I ask you to provide the terminal settings (gdb console, internal console, several external consoles) as a PR to https://github.com/WebFreak001/code-debug ? This is a quite important feature that I'm missing badly there.

2024-01-17 00:45 UTC, marcsosduma commented
Hello Simon!
Is this what you need?

launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "COBOL debugger",
            "type": "gdb",
            "request": "launch",
            "cobcargs": [
                "-free",
                "-x"
            ],
            "coverage": false,
            "gdbtty": true,
            "verbose": true,
            "group": ["subsample.cbl","subsubsample.cbl"]
        },
        {
            "name": "COBOL debugger attach local",
            "type": "gdb",
            "request": "attach",
            "cobcargs": [
                "-free",
                "-x"
            ],
            "pid": "${input:pid}"
        },
        {
            "name": "COBOL debugger attach remote",
            "type": "gdb",
            "request": "attach",
            "cobcargs": [
                "-free",
                "-x"
            ],
            "remoteDebugger": "${input:remoteDebugger}"
        }
    ]
}

![image](https://github.com/OlegKunitsyn/gnucobol-debug/assets/31162117/278891dc-9b68-4c5f-b526-a7e259e038d3)

2024-01-17 06:12 UTC, GitMensch commented
The configuration is fine - I've asked you to contribute similar code you've added to this extension (all `gdbtty` related ones) to another extension (that is for general GDB debugging).

2024-01-17 11:27 UTC, marcsosduma commented
Good morning, Simon! I can definitely try. It will be a pleasure.

2025-11-02 00:44 UTC, closed without merging